import { Prisma } from '../lib/generated/prisma';

export const productsData: Prisma.ProductCreateInput[] = [
    {
        slug: 'ovulation-strip-kit-50pk',
        name: 'Ovulation Test Strips Kit - 50 Pack',
        description: 'Bulk pack of accurate and easy-to-use ovulation test strips for daily tracking.',
        category: 'OVULATION_TESTS',
        price: 29.99,
        rating: 4.5,
        numReviews: 320,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Economical bulk pack for long-term tracking.'
    },
    {
        slug: 'prenatal-complete',
        name: 'Complete Prenatal Vitamin Complex',
        description: 'Comprehensive prenatal vitamin with folate, DHA, and essential minerals.',
        category: 'SUPPLEMENTS',
        price: 34.99,
        rating: 4.8,
        numReviews: 425,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Doctor-recommended complete prenatal formula.'
    },
    {
        slug: 'fertility-monitor-advanced',
        name: 'Advanced Fertility Monitor',
        description: 'Digital fertility monitor with temperature and hormone tracking.',
        category: 'APPS_TRACKERS',
        price: 159.99,
        rating: 4.7,
        numReviews: 890,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Advanced technology for precise ovulation tracking.'
    },
    {
        slug: 'conception-vitamins-men',
        name: 'Male Fertility Support Vitamins',
        description: 'Specially formulated vitamins to support male reproductive health.',
        category: 'SUPPLEMENTS',
        price: 28.99,
        rating: 4.4,
        numReviews: 230,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Supports sperm health and male fertility.'
    },
    {
        slug: 'pregnancy-test-digital',
        name: 'Digital Pregnancy Test',
        description: 'Clear digital results with smart countdown feature.',
        category: 'PREGNANCY_TESTS',
        price: 15.99,
        rating: 4.6,
        numReviews: 675,
        imageUrl: 'https://millenniummedicalcare.com/wp-content/uploads/pregnancy-testing-2311.jpg',
        expertSummary: 'No more guessing with clear digital results.'
    },
    {
        slug: 'fertility-tea-blend',
        name: 'Fertility Support Herbal Tea',
        description: 'Natural herbal tea blend supporting reproductive health.',
        category: 'SUPPLEMENTS',
        price: 18.99,
        rating: 4.3,
        numReviews: 145,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Traditional herbs known to support fertility.'
    },
    {
        slug: 'ovulation-microscope',
        name: 'Saliva Fertility Microscope',
        description: 'Personal microscope for tracking fertility through saliva patterns.',
        category: 'OVULATION_TESTS',
        price: 39.99,
        rating: 4.1,
        numReviews: 89,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Natural method for fertility awareness.'
    },
    {
        slug: 'fertility-supplement-combo',
        name: 'Fertility Supplement Bundle',
        description: 'Complete supplement pack for both partners.',
        category: 'SUPPLEMENTS',
        price: 64.99,
        rating: 4.7,
        numReviews: 234,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Comprehensive fertility support for couples.'
    },
    {
        slug: 'basal-thermometer',
        name: 'Digital Basal Thermometer',
        description: 'Ultra-sensitive thermometer for fertility tracking.',
        category: 'APPS_TRACKERS',
        price: 24.99,
        rating: 4.5,
        numReviews: 567,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Essential tool for temperature tracking.'
    },
    {
        slug: 'fertility-lube-premium',
        name: 'Premium Fertility Lubricant',
        description: 'Premium fertility-friendly lubricant with optimal pH.',
        category: 'FERTILITY_FRIENDLY',
        price: 19.99,
        rating: 4.6,
        numReviews: 432,
        imageUrl: 'https://pictures-nigeria.jijistatic.net/125376414_NjIwLTc1Mi0wZDFhNzM5MWFh.webp',
        expertSummary: 'Clinically tested for optimal conception support.'
    },
    {
        slug: 'ovulation-test-digital',
        name: 'Digital Ovulation Predictor',
        description: 'Advanced digital ovulation test with clear results.',
        category: 'OVULATION_TESTS',
        price: 32.99,
        rating: 4.7,
        numReviews: 289,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Digital accuracy for precise ovulation tracking.'
    },
    {
        slug: 'fertility-cookbook',
        name: 'Fertility Diet Cookbook',
        description: 'Recipe collection supporting reproductive health.',
        category: 'OTHER',
        price: 24.99,
        rating: 4.4,
        numReviews: 156,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Nutritionist-approved recipes for fertility.'
    },
    {
        slug: 'cycle-tracking-journal',
        name: 'Fertility Tracking Journal',
        description: 'Physical journal for tracking cycles and symptoms.',
        category: 'APPS_TRACKERS',
        price: 16.99,
        rating: 4.3,
        numReviews: 178,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Comprehensive tracking in paper format.'
    },
    {
        slug: 'fertility-massage-oil',
        name: 'Fertility Massage Oil',
        description: 'Natural oil blend for fertility massage.',
        category: 'FERTILITY_FRIENDLY',
        price: 22.99,
        rating: 4.2,
        numReviews: 92,
        imageUrl: 'https://pictures-nigeria.jijistatic.net/125376414_NjIwLTc1Mi0wZDFhNzM5MWFh.webp',
        expertSummary: 'Aromatherapy blend for reproductive wellness.'
    },
    {
        slug: 'ovulation-test-bulk-100',
        name: 'Ovulation Test Strips - 100 Pack',
        description: 'Bulk pack for long-term tracking needs.',
        category: 'OVULATION_TESTS',
        price: 49.99,
        rating: 4.6,
        numReviews: 543,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Best value for long-term testing needs.'
    },
    {
        slug: 'fertility-tracking-bracelet',
        name: 'Smart Fertility Tracking Bracelet',
        description: 'Wearable device that tracks temperature and other fertility indicators.',
        category: 'APPS_TRACKERS',
        price: 199.99,
        rating: 4.7,
        numReviews: 432,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Advanced wearable technology for precise cycle tracking.'
    },
    {
        slug: 'fertility-multivitamin-women',
        name: 'Women\'s Fertility Multivitamin',
        description: 'Complete daily vitamin support for women trying to conceive.',
        category: 'SUPPLEMENTS',
        price: 39.99,
        rating: 4.8,
        numReviews: 567,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Comprehensive nutrient support for reproductive health.'
    },
    {
        slug: 'ovulation-microscope-pro',
        name: 'Professional Ovulation Microscope',
        description: 'High-quality microscope for tracking fertility through saliva ferning patterns.',
        category: 'OVULATION_TESTS',
        price: 79.99,
        rating: 4.3,
        numReviews: 234,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Professional-grade fertility tracking tool.'
    },
    {
        slug: 'fertility-tea-bundle',
        name: 'Fertility Tea Collection Bundle',
        description: 'Set of different herbal teas supporting reproductive health.',
        category: 'SUPPLEMENTS',
        price: 45.99,
        rating: 4.5,
        numReviews: 189,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Variety of traditional fertility-supporting teas.'
    },
    {
        slug: 'pregnancy-test-early-50pk',
        name: 'Early Detection Pregnancy Tests - 50 Pack',
        description: 'Bulk pack of sensitive early pregnancy detection tests.',
        category: 'PREGNANCY_TESTS',
        price: 39.99,
        rating: 4.7,
        numReviews: 892,
        imageUrl: 'https://millenniummedicalcare.com/wp-content/uploads/pregnancy-testing-2311.jpg',
        expertSummary: 'Economical bulk pack for frequent testing.'
    },
    {
        slug: 'fertility-supplement-dhea',
        name: 'DHEA Fertility Supplement',
        description: 'Supplement supporting hormone balance and egg quality.',
        category: 'SUPPLEMENTS',
        price: 29.99,
        rating: 4.4,
        numReviews: 167,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Hormone support supplement for reproductive health.'
    },
    {
        slug: 'ovulation-predictor-advanced',
        name: 'Advanced Digital Ovulation Predictor',
        description: 'Digital ovulation predictor with dual hormone tracking.',
        category: 'OVULATION_TESTS',
        price: 59.99,
        rating: 4.6,
        numReviews: 445,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Tracks both LH and estrogen for precise prediction.'
    },
    {
        slug: 'fertility-massage-kit',
        name: 'Fertility Massage Kit',
        description: 'Complete kit for fertility massage including oils and guide.',
        category: 'FERTILITY_FRIENDLY',
        price: 49.99,
        rating: 4.3,
        numReviews: 156,
        imageUrl: 'https://pictures-nigeria.jijistatic.net/125376414_NjIwLTc1Mi0wZDFhNzM5MWFh.webp',
        expertSummary: 'Professional-grade fertility massage tools and guidance.'
    },
    {
        slug: 'cycle-tracking-thermometer',
        name: 'Smart Basal Thermometer',
        description: 'Bluetooth-enabled basal thermometer with app connectivity.',
        category: 'APPS_TRACKERS',
        price: 89.99,
        rating: 4.7,
        numReviews: 678,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Automatic temperature tracking and cycle analysis.'
    },
    {
        slug: 'fertility-supplement-coq10',
        name: 'CoQ10 Fertility Supplement',
        description: 'High-quality CoQ10 supplement for egg quality support.',
        category: 'SUPPLEMENTS',
        price: 34.99,
        rating: 4.5,
        numReviews: 234,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'Supports cellular energy and egg quality.'
    },
    {
        slug: 'pregnancy-test-digital-pack',
        name: 'Digital Pregnancy Tests - 3 Pack',
        description: 'Clear digital results with smart countdown feature.',
        category: 'PREGNANCY_TESTS',
        price: 24.99,
        rating: 4.8,
        numReviews: 567,
        imageUrl: 'https://millenniummedicalcare.com/wp-content/uploads/pregnancy-testing-2311.jpg',
        expertSummary: 'Easy-to-read digital results with high accuracy.'
    },
    {
        slug: 'fertility-tracking-subscription',
        name: 'Premium Fertility Tracking Subscription',
        description: 'Annual subscription to advanced fertility tracking platform.',
        category: 'APPS_TRACKERS',
        price: 79.99,
        rating: 4.9,
        numReviews: 1234,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Comprehensive digital fertility tracking solution.'
    },
    {
        slug: 'fertility-friendly-lube-pack',
        name: 'Fertility Lubricant Multi-Pack',
        description: 'Value pack of fertility-friendly personal lubricant.',
        category: 'FERTILITY_FRIENDLY',
        price: 39.99,
        rating: 4.4,
        numReviews: 345,
        imageUrl: 'https://pictures-nigeria.jijistatic.net/125376414_NjIwLTc1Mi0wZDFhNzM5MWFh.webp',
        expertSummary: 'pH-balanced lubricant optimized for conception.'
    },
    {
        slug: 'ovulation-test-combo-kit',
        name: 'Ovulation Test Combo Kit',
        description: 'Combination of strips and digital tests for comprehensive tracking.',
        category: 'OVULATION_TESTS',
        price: 49.99,
        rating: 4.6,
        numReviews: 567,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Complete ovulation testing solution.'
    },
    {
        slug: 'fertility-supplement-bundle',
        name: 'Complete Fertility Supplement Bundle',
        description: 'Comprehensive bundle of essential fertility supplements.',
        category: 'SUPPLEMENTS',
        price: 89.99,
        rating: 4.7,
        numReviews: 432,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/vitamins-pills-bottle-1296x728-header-1296x728.jpg',
        expertSummary: 'All-in-one fertility supplement solution.'
    },
    {
        slug: 'pregnancy-test-strips-bulk',
        name: 'Pregnancy Test Strips - 100 Pack',
        description: 'Economical bulk pack of early detection test strips.',
        category: 'PREGNANCY_TESTS',
        price: 29.99,
        rating: 4.5,
        numReviews: 789,
        imageUrl: 'https://millenniummedicalcare.com/wp-content/uploads/pregnancy-testing-2311.jpg',
        expertSummary: 'Best value for frequent pregnancy testing.'
    },
    {
        slug: 'fertility-tracking-watch',
        name: 'Fertility Tracking Smart Watch',
        description: 'Wearable device with advanced fertility tracking features.',
        category: 'APPS_TRACKERS',
        price: 299.99,
        rating: 4.8,
        numReviews: 567,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Comprehensive fertility tracking on your wrist.'
    },
    {
        slug: 'fertility-friendly-moisturizer',
        name: 'Fertility-Friendly Personal Moisturizer',
        description: 'Natural, fertility-safe personal moisturizer.',
        category: 'FERTILITY_FRIENDLY',
        price: 19.99,
        rating: 4.3,
        numReviews: 234,
        imageUrl: 'https://pictures-nigeria.jijistatic.net/125376414_NjIwLTc1Mi0wZDFhNzM5MWFh.webp',
        expertSummary: 'Gentle, fertility-safe intimate care.'
    },
    {
        slug: 'ovulation-predictor-premium',
        name: 'Premium Ovulation Prediction Kit',
        description: 'High-end digital ovulation predictor with advanced features.',
        category: 'OVULATION_TESTS',
        price: 79.99,
        rating: 4.7,
        numReviews: 678,
        imageUrl: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/04/ovulation_strips-1296x728-header.jpg',
        expertSummary: 'Professional-grade ovulation prediction.'
    },
    {
        slug: 'fertility-journal-deluxe',
        name: 'Deluxe Fertility Tracking Journal',
        description: 'Premium physical journal for comprehensive fertility tracking.',
        category: 'OTHER',
        price: 29.99,
        rating: 4.6,
        numReviews: 234,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Beautiful and practical fertility tracking journal.'
    },
    {
        slug: 'fertility-education-course',
        name: 'Online Fertility Education Course',
        description: 'Comprehensive online course about fertility and conception.',
        category: 'OTHER',
        price: 199.99,
        rating: 4.8,
        numReviews: 567,
        imageUrl: 'https://img2.exportersindia.com/product_images/bc-full/2020/4/6809924/mobile-application-development-services-1586953948-5373882.jpg',
        expertSummary: 'Expert-led fertility education program.'
    }
]; 